/** **********GET POKEMON LIST*********** */
export const GET_POKEMON_LIST = 'GET_POKEMON_LIST';

/** **********GET POKEMON TYPES*********** */
export const GET_POKEMON_TYPES = 'GET_POKEMON_TYPES';

/** **********GET AND CLEAR SELECTED POKEMON*********** */
export const GET_POKEMON_DETAILS = 'GET_POKEMON_DETAILS';
export const CLEAR_POKEMON_DETAILS = 'CLEAR_POKEMON_DETAILS';

/** **********GET FILTER POKEMON LIST*********** */
export const SET_OFFSET_LIMIT = 'SET_OFFSET_LIMIT';
export const LOAD_FILTER_DATA = 'LOAD_FILTER_DATA';
export const GET_POKEMON_FILTER_LIST = 'GET_POKEMON_FILTER_LIST';
export const GET_POKEMON_SEARCH_RESULT = 'GET_POKEMON_SEARCH_RESULT';
